name = "CachedFunctions"
uuid = "ed268df6-2d29-4139-a3e0-ddeb8be80dc7"
authors = ["longemen3000"]
version = "0.1.1"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
